#!/usr/bin/env python3
# 这个奇怪的脚本用来启动, 关闭测试环境
# run start    启动测试用的机器
# run stop      关闭测试用的机器
# 就这么些个功能

import sys, os

def 错误():
    print("运行失败")
    exit(1)

if len(sys.argv) != 2:
    错误()
if sys.argv[1] == "start":
    if os.system("docker start helloworld01 helloworld02 helloworld03"):
        错误()
    if os.system("docker exec helloworld01 /usr/sbin/sshd"):
        错误()
    if os.system("docker exec helloworld02 /usr/sbin/sshd"):
        错误()
    if os.system("docker exec helloworld03 /usr/sbin/sshd"):
        错误()
        
elif sys.argv[1] == "stop":
    os.system("docker stop helloworld01 helloworld02 helloworld03")
else:
    错误()